/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.EnumStatusTarefa;
import domain.Item;
import domain.Tarefa;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe Cardozo
 */
public class GuiTarefa extends javax.swing.JDialog {

    private Tarefa tarefa;
    private boolean alterar = false;
    /**
     * Creates new form GuiTarefa
     */
    public GuiTarefa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    private void exibirTabela() {
        TxtPercentualConcluido.setText(Integer.toString(tarefa.getPercentualConcluido()));
        DefaultTableModel tblItem = (DefaultTableModel) TblItem.getModel();
        int qtdLinhas = tblItem.getRowCount();

        for (int i = qtdLinhas - 1; i >= 0; i--) {
            tblItem.removeRow(0);
        }
        for (Item novoItem : tarefa.getItens()) {
            Object linha[] = {novoItem,  novoItem.getDataExecucao(), novoItem.getPercentualCorrespondente()};
            tblItem.addRow(linha);
        }
    }
    
    public void setAlterar(boolean alterar) {
        this.alterar = alterar;
    }
    public Tarefa getTarefa() {
        return tarefa;
    }
    public void setTarefa(Tarefa tarefa) {
        this.tarefa = tarefa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblTarefa = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        TxtPercentualConcluido = new javax.swing.JTextField();
        txtDetalhamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblItem = new javax.swing.JTable();
        BtnTarefa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TxtData = new javax.swing.JFormattedTextField();
        jToolBar1 = new javax.swing.JToolBar();
        BtnNovoItem = new javax.swing.JButton();
        BtnAlterarItem = new javax.swing.JButton();
        BtnRemoverItem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        TblTarefa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sexo", "Endereço", "Idade"
            }
        ));
        jScrollPane1.setViewportView(TblTarefa);

        jLabel4.setText("Controle");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeActionPerformed(evt);
            }
        });

        TxtPercentualConcluido.setEditable(false);
        TxtPercentualConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPercentualConcluidoActionPerformed(evt);
            }
        });

        txtDetalhamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetalhamentoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Percentual Concluido");

        jLabel3.setText("Detalhamento");

        TblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Data", "Porcentagem"
            }
        ));
        jScrollPane2.setViewportView(TblItem);

        BtnTarefa.setText("GravarTarefa");
        BtnTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTarefaActionPerformed(evt);
            }
        });

        jLabel5.setText("Data Limite");

        try {
            TxtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDataActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        BtnNovoItem.setText("Novo");
        BtnNovoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoItemActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnNovoItem);

        BtnAlterarItem.setText("Alterar");
        BtnAlterarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarItemActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnAlterarItem);

        BtnRemoverItem.setText("Remover");
        BtnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoverItemActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnRemoverItem);

        jLabel6.setText("Tarefas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnTarefa)))
                            .addComponent(jLabel6))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtPercentualConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDetalhamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(TxtPercentualConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDetalhamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTarefa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeActionPerformed

    private void TxtPercentualConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPercentualConcluidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPercentualConcluidoActionPerformed

    private void txtDetalhamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetalhamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetalhamentoActionPerformed

    private void BtnTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTarefaActionPerformed
        // TODO add your handling code here:
        if (!alterar) {
            tarefa = new Tarefa();
            TxtPercentualConcluido.setText(Integer.toString(tarefa.getPercentualConcluido()));
        }
        tarefa.setDetalhamento(txtDetalhamento.getText());
        tarefa.setNome(TxtNome.getText());

        //if(tarefa.getStatus() == EnumStatusTarefa.concluida){
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            tarefa.setDataLimite(LocalDate.parse(TxtData.getText(), formatter));
        //}
    }//GEN-LAST:event_BtnTarefaActionPerformed

    private void BtnNovoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoItemActionPerformed
        // TODO add your handling code here:
        GuiItem g = new GuiItem(null, true);
        g.setVisible(true);
        g.setAlterar(false);
        tarefa.addItem(g.getItem());
        exibirTabela();
    }//GEN-LAST:event_BtnNovoItemActionPerformed

    private void BtnAlterarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarItemActionPerformed
        // TODO add your handling code here:
        Item item = (Item) TblItem.getValueAt(TblItem.getSelectedRow(), 0);
        GuiItem g = new GuiItem(null, true);
        g.setItem(item);
        g.setAlterar(true);
        g.setVisible(true);
        tarefa.setPercentualConcluido(item.getPercentualCorrespondente());
        exibirTabela();
    }//GEN-LAST:event_BtnAlterarItemActionPerformed

    private void BtnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoverItemActionPerformed
        // TODO add your handling code here:
        Item item = (Item) TblItem.getValueAt(TblItem.getSelectedRow(), 0);
        tarefa.removeItem(item);
        exibirTabela();
    }//GEN-LAST:event_BtnRemoverItemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        /*if(tarefa != null){
            if(tarefa.getStatus() != EnumStatusTarefa.concluida){
                TxtData.setEditable(false);
            }
        }else{
            TxtData.setEditable(false);
        }*/
        if (alterar) {
            TxtNome.setText(tarefa.getNome());
            TxtPercentualConcluido.setText(Integer.toString(tarefa.getPercentualConcluido()));
            txtDetalhamento.setText(tarefa.getDetalhamento());
            
            //if(tarefa.getStatus() == EnumStatusTarefa.concluida){
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            TxtData.setText(tarefa.getDataLimite().format(formatter));
            //}
            exibirTabela();
        }
    }//GEN-LAST:event_formWindowOpened

    private void TxtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GuiTarefa dialog = new GuiTarefa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterarItem;
    private javax.swing.JButton BtnNovoItem;
    private javax.swing.JButton BtnRemoverItem;
    private javax.swing.JButton BtnTarefa;
    private javax.swing.JTable TblItem;
    private javax.swing.JTable TblTarefa;
    private javax.swing.JFormattedTextField TxtData;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtPercentualConcluido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtDetalhamento;
    // End of variables declaration//GEN-END:variables
}
